apiVersion: one2n.com/v1
kind: RabbitMQConsumer
metadata:
  name: one2n-consumer
  namespace: poc
spec:
  rabbitmqHost: "rabbitmq-service"
  rabbitmqQueue: "one2n"
  rabbitmqUser: "guest"
  rabbitmqPassword: "test@123"
  minReplicas: 1
  maxReplicas: 10
  threshold: 15
