apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # RabbitMQ port for messaging
            - containerPort: 15672 # Management UI
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "test@123"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: poc
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672      # RabbitMQ messaging port
      targetPort: 5672
    - name: management
      port: 15672     # RabbitMQ management UI port
      targetPort: 15672
