apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: poc
  labels:
    app: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: sahil2898/one2n-mqtt-consumer:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_QUEUE
          value: "one2n"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "test@123"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Always
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-service
#   namespace: poc
#   labels:
#     app: rabbitmq
# spec:
#   ports:
#   - name: amqp
#     port: 5672
#     targetPort: 5672
#   selector:
#     app: rabbitmq
