apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-controller
  namespace: poc
  labels:
    app: rabbitmq-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-controller
  template:
    metadata:
      labels:
        app: rabbitmq-controller
    spec:
      serviceAccountName: rabbitmq-controller
      containers:
      - name: rabbitmq-controller
        image: sahil2898/one2n-controller:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.default.svc.cluster.local"
        - name: RABBITMQ_QUEUE
          value: "my-queue"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: CRD_GROUP
          value: "one2n.com"
        - name: CRD_VERSION
          value: "v1"
        - name: CRD_PLURAL
          value: "rabbitmqconsumers"
        - name: NAMESPACE
          value: "default"
        - name: MIN_REPLICAS
          value: "1"
        - name: MAX_REPLICAS
          value: "10"
        - name: THRESHOLD
          value: "100"
